logging:
  level: INFO
  loggers:
    com.dropwizard: DEBUG

mongoServer:
  uri: mongodb+srv://admin:vNQbwiBXdYj6nDZi@cluster0.lohj3.mongodb.net/minesweeper
  database: minesweeper
swagger:
  resourcePackage: com.dropwizard.resources
  scan: true
  info:
    version: "1.0.0"
    title: "Minesweeper API"
    description: "Minesweeper"
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Mayra Palomares"